### ISSUE TITLE
Clean up August Technical Roadmap and create simple visuals for how the work we're doing now fits overall vision

### ISSUE THREAD

**Issue by bs** [earthspecies/project#37]
https://docs.google.com/document/d/1NY_FC4M4NvBpAX66wsETQHr86rg7BGS0uqElG6UyMgg/edit?usp=sharing

It's clear we need to illustrate how what we've chosen to tackle now fits into the bigger picture (gotten this feedback on the ii.io workshop) and create a publicly available artifact from our August brainstorming session.

@aza, this seems like something that could use your superpowers.

Note: I re-labeled the [2018 AI Roadmap](https://github.com/earthspecies/project/blob/main/roadmaps/ai.md) in the [/roadmaps README](https://github.com/earthspecies/project/tree/main/roadmaps) to better reflect its adherence to the passage of time.

**Comment by mhagiwara** [comment]
Closing this as we updated the latest roadmap
