### ISSUE TITLE
404 urls

### ISSUE THREAD

**Issue by bambooforest** [earthspecies/project#4]
On pages:

https://earthspecies.org/
https://earthspecies.org/about

the linked text:

* "technical details" 
* "technical roadmap" 
* "read more on the technical details"
* "on Github"

points to (now 404):

https://github.com/earthspecies/roadmaps/blob/master/ai.md

Refer to:

https://github.com/earthspecies/project/blob/master/roadmaps/ai.md

Cheers.

**Comment by bs** [comment]
Thank you, @bambooforest! We changed repo names for the roadmap and just saw today that it was not returning a 301.

**Comment by aza** [comment]
Thank you @bambooforest! The links should now be fixed.
