### ISSUE TITLE
Request for info about embeddings for whale vocalizations

### ISSUE THREAD

**Issue by John-Ragland** [earthspecies/project#43]
Hi, I'm a PhD student studying machine learning and ocean acoustics. I'm currently working on research that involves long-term acoustic recordings that have quite a lot of whale vocalizations. In reading the project map I came across this quote:

"At the same time, we are taking a bottom-up approach: we can learn a lot by comparing the embedding structures of, say, many individual sperm whales: analyzing how they change between individuals and pods; amongst clans and cultures; between captive populations and wild ones; over time; and from one species to a related species."

I'm super interested in this and would love if someone could point me in the direction of some papers or code that relates to this quote above.

Thanks!

**Comment by radekosmulski** [comment]
Hi John!

A pleasure to meet you! 🙂 

Creating embeddings from animal vocalizations is still in the research phase - it is something that we are actively working towards. But we have a good idea of what it should enable.

If you'd like to familiarize yourself more with the concept of an embedding, here are a couple good papers to read:
* [A very early, seminal paper by one of the founder's of the field on what an embedding is](http://www.cs.toronto.edu/~hinton/absps/families.pdf)
* [A breakthrough paper on constructing embeddings from text](https://arxiv.org/abs/1301.3781)
* [A fascinating paper demonstrating translation between languages, without the use of rosetta stone, relying on embeddings](https://arxiv.org/abs/1710.04087)

One of the projects that we are working on, where we are attempting to tackle creating the embeddings, is this [one](https://github.com/earthspecies/unsupervised-speech-translation). This is still however a work in progress - there are many research questions that arise on the path to creating embeddings for animal vocalizations.

Specifically, with regards to sperm whales, we share this [repository](https://github.com/earthspecies/sperm-whale-clan-and-coda-detection). In this [notebook](https://github.com/earthspecies/sperm-whale-clan-and-coda-detection/blob/main/06_Clan_and_coda_type_detection_with_Random_Forest.ipynb) we are taking a deep dive on analyzing inter-click intervals - not sure if this is something that might be helpful to your research.

Let me know if you have any other questions 🙂 
Radek

**Comment by John-Ragland** [comment]
Thanks for the reply! I'll be sure to check out these sources!
